"""Static fallback station data for key lines."""

STATION_FALLBACKS = {
    "metro": {
        "1": [
            {"name": "La Défense"},
            {"name": "Esplanade de La Défense"},
            {"name": "Charles de Gaulle – Étoile"},
            {"name": "Champs-Élysées – Clemenceau"},
            {"name": "Palais Royal – Musée du Louvre"},
            {"name": "Châtelet"},
            {"name": "Bastille"},
            {"name": "Gare de Lyon"},
            {"name": "Nation"},
            {"name": "Château de Vincennes"},
        ],
        "14": [
            {"name": "Saint-Denis Pleyel"},
            {"name": "Mairie de Saint-Ouen"},
            {"name": "Saint-Lazare"},
            {"name": "Madeleine"},
            {"name": "Pyramides"},
            {"name": "Châtelet"},
            {"name": "Gare de Lyon"},
            {"name": "Bercy"},
            {"name": "Olympiades"},
            {"name": "Orly"},
        ],
    },
    "rer": {
        "A": [
            {"name": "Saint-Germain-en-Laye"},
            {"name": "Nanterre-Préfecture"},
            {"name": "La Défense"},
            {"name": "Charles de Gaulle – Étoile"},
            {"name": "Auber"},
            {"name": "Châtelet – Les Halles"},
            {"name": "Gare de Lyon"},
            {"name": "Nation"},
            {"name": "Marne-la-Vallée Chessy"},
        ],
        "B": [
            {"name": "Aéroport Charles de Gaulle 2"},
            {"name": "Parc des Expositions"},
            {"name": "Le Bourget"},
            {"name": "Gare du Nord"},
            {"name": "Châtelet – Les Halles"},
            {"name": "Denfert-Rochereau"},
            {"name": "Bourg-la-Reine"},
            {"name": "Massy-Palaiseau"},
            {"name": "Saint-Rémy-lès-Chevreuse"},
        ],
    },
    "tram": {
        "T3a": [
            {"name": "Pont du Garigliano"},
            {"name": "Porte de Versailles"},
            {"name": "Porte de Vanves"},
            {"name": "Cité Universitaire"},
            {"name": "Porte d'Italie"},
            {"name": "Porte de Charenton"},
            {"name": "Porte de Vincennes"},
        ],
        "T13": [
            {"name": "Saint-Germain-en-Laye"},
            {"name": "L'Etang-la-Ville"},
            {"name": "Noisy-le-Roi"},
            {"name": "Bailly"},
            {"name": "Versailles-Chantiers"},
        ],
    },
    "transilien": {
        "L": [
            {"name": "Paris Saint-Lazare"},
            {"name": "Clichy – Levallois"},
            {"name": "Courbevoie"},
            {"name": "La Défense"},
            {"name": "Suresnes – Mont-Valérien"},
            {"name": "Saint-Cloud"},
            {"name": "Garches – Marnes-la-Coquette"},
            {"name": "Versailles Rive Droite"},
        ],
        "J": [
            {"name": "Paris Saint-Lazare"},
            {"name": "Argenteuil"},
            {"name": "Herblay"},
            {"name": "Conflans-Sainte-Honorine"},
            {"name": "Gisors"},
        ],
    },
}
