version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ratp
      POSTGRES_PASSWORD: ratp
      POSTGRES_DB: ratp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://ratp:ratp@db:5432/ratp
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      VMTR_SOCKET_ENABLED: "True"
      SYSTEM_API_TOKEN: changeme
    depends_on:
      - db
      - kafka
    ports:
      - "8000:8000"

  scheduler:
    build:
      context: ./backend
    command: ["python", "-m", "backend.workers.scheduler"]
    environment:
      DATABASE_URL: postgresql+asyncpg://ratp:ratp@db:5432/ratp
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      VMTR_SOCKET_ENABLED: "True"
      SCHEDULER_INTERVAL_SECONDS: 120
    depends_on:
      - backend
      - kafka

  worker:
    build:
      context: ./backend
    command: ["python", "-m", "backend.workers.worker"]
    environment:
      DATABASE_URL: postgresql+asyncpg://ratp:ratp@db:5432/ratp
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      VMTR_SOCKET_ENABLED: "True"
    depends_on:
      - backend
      - kafka

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_BACKEND_HOST: backend
      NEXT_PUBLIC_BACKEND_PORT: "8000"
      NEXT_PUBLIC_SYSTEM_API_KEY: changeme
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
